const News = {
    "news": [
        {"title": "Ózbekstan ulıwma úyimiz!", "text_short": "Muhammed al-Xorezmiy atındaǵı TITU Nókis filialında \"Ózbekstan - ulıwma úyimiz\" atamasındaǵı doslıq", "text_full": "Ózbekstan ulıwma úyimiz! <br/><br/> Muhammed al-Xorezmiy atındaǵı TITU Nókis filialında \"Ózbekstan - ulıwma úyimiz\" atamasındaǵı doslıq festivalı bolıp ótti. <br><br>Búgin, 1-may kúni Muhammed al-Xorezmiy atındaǵı TITU Nókis filialında \"Ózbekstan - ulıwma úyimiz\" atamasındaǵı doslıq festivalı joqarı shólkemleskenlik penen bolıp ótti. Festivaldı TITU Nókis filialı Oqıw isleri boyınsha direktor orınbasarı Xayratdin Seytkamalov ashıp berdi hám alıp bardı. Sonday-aq, Qaraqalpaqstan Respublikası Joqarı Keńesi Komitet baslıǵı Tajibay Romanov, Qaraqalpaqstan Respublikası Joqarı Keńesi deputatı Venera Kalenova, Nókis qalası \"Nuranıy\" qorı baslıǵı Karamatdin Kalenderov, Xalıq deputatları Nókis qalalıq Keńesi deputatı Gawhar Qudiyarova hám Qaraqalpaqstan Musılmanlar qaziyatı qazısı orınbasarı Aybek Jolawshiev sózge shıqtı.<br><br>Bul festivalda mámleketimizdegi 130 dan aslam millet wákilleri bir shańaraqtıń perzentlerindey tatıwlıqta, awızbirshilikte jasap túrli tarawlarda nátiyjeli miynet etip atırǵanı ayqın sáwlelengen.", "img": "https://tatunf.uz/images/news/2024/may/1/4.jpg"},

        {"title": "\"Jaslar akademiyası forumı\" bolıp ótti.", "text_short": "30-aprel kúni Nókis kánshilik institutında Ájiniyaz atındaǵı NMPI, Muhammed al-Xorezmiy atındaǵı TITU", "text_full": "\"Jaslar akademiyası forumı\" bolıp ótti.<br/><br/>30-aprel kúni Nókis kánshilik institutında Ájiniyaz atındaǵı NMPI, Muhammed al-Xorezmiy atındaǵı TITU Nókis filialı hám basqa da joqarı oqıw orınları student-jasları qatnasıwında \"Jaslar akademiyası forumı\" bolıp ótti.<br/><br/>Forumda Jaslar akademiyasınıń Qaraqalpaqstan Respublikası aymaqlıq lideri Q.Jalǵasbaeva Jaslar akademiyası, akademiya tárepinen járiyalanǵan tańlawlar hám házirgi kúnde liderler tárepinen ámelge asırılıp atırǵan is-ilajlar boyınsha maǵlıwmatlar berip ótti.<br/><br/>Onda Muhammed al-Xorezmiy atındaǵı TITU Nókis filialı student-jasları ózleriniń innovacion joybarları menen qatnastı hám bolıp ótken seminar-treninglerden ózlerine paydalı bolǵan maǵlıwmatlar alıp, basqa da JOO menen pikir almastı.<br/><br/>Forumda filialımız 3-kurs studenti Jalǵasbaeva Qundız Jaslar akademiyası haqqında óz prezentaciyası menen qatnastı. Maǵlıwmat ornında, Jalǵasbaeva Qundız Jaslar akademiyası aymaqlıq lideri bolıp esaplanadı.", "img": "https://tatunf.uz/images/news/2024/may/1/8.jpg"},

        {"title": "Búgin erte tańnan paytaxtımız boylap «Bir watanda, bir waqıtta, birdey aralıqqa, bir maqsette – birgelikte juwıramız» súreni tiykarında «Jańa nápes» juwırıw marafonı bolıp ótti.", "text_short": "Marafonda bárshe qatnasıwshılar qatarında Muhammed al-Xorezmiy atındaģı TITU Nókis filialı basshıları, ziyrek student-jasları hám tyutorlarınan", "text_full": "Búgin erte tańnan paytaxtımız boylap «Bir watanda, bir waqıtta, birdey aralıqqa, bir maqsette – birgelikte juwıramız» súreni tiykarında «Jańa nápes» juwırıw marafonı bolıp ótti.<br/><br/>Marafonda bárshe qatnasıwshılar qatarında Muhammed al-Xorezmiy atındaģı TITU Nókis filialı basshıları, ziyrek student-jasları hám tyutorlarınan dúzilgen jámáát belsendilik penen qatnastı. <br/><br/>Eń quwanıshlısı juwırıw marafonında para olimpiada jónelisi boyınsha filialımız \"Kompyuter injiniringi\" fakulteti 3-kurs studenti Sarıbaev Nursultan 1-orın, Usmonjonov Xusniddin \"Jeńiske bolģan talpınısı ushın\" nominaciyaların qolģa kirgizip, húrmet jarlıģı hám estelik sawģaları menen sıylıqlandı.<br/><br/>Bizde óz gezeginde filialımız sportshılarınıń qolǵa kirgizgen jetiskenligi menen qutlıqlap, aldaǵı oqıwlarında tabıslar tilep qalamız.", "img": "https://tatunf.uz/images/news/2024/may/1/11.jpg"},

        {"title": "Mutoala loyihasi taqdimoti bilan tanishmoqda", "text_short": "Ayni damda, Muhammad al-Xorazmiy nomidagi TATU Nukus filiali talaba-yoshlari tadbir doirasida O'zbek xalqi Jadidlarining ilm-ma'rifat ulashish maqsadida hayot yo'llarida bosib o'tgan qiyinchiliklarini aks ettirgan spektaklni tomosha qilmoqda.", "text_full": "Mutoala loyihasi taqdimoti bilan tanishmoqda<br/><br/>Ayni damda, Muhammad al-Xorazmiy nomidagi TATU Nukus filiali talaba-yoshlari tadbir doirasida O'zbek xalqi Jadidlarining ilm-ma'rifat ulashish maqsadida hayot yo'llarida bosib o'tgan qiyinchiliklarini aks ettirgan spektaklni tomosha qilmoqda.<br/><br/>Spektakldan talaba-yoshlar o'zlariga kerakli bo'lgan juda ham qimmatli ma'naviy-ma'rifiy ozuqa olishdi.", "img": "https://tatunf.uz/images/news/2024/april/5/6.jpg"},

        {"title": "\"Xon atlas\" ilaji bolıp ótti", "text_short": "Filialımızda hayal-qızlarımızdıń milliy kóyleklerinde xalqımızdıń mıń ásirlik ótmishi, úrp-ádet hám dástúrleri sáwlelendirilgen kórinisler jámlengen \"Xon atlas\" hápteligi sheńberinde ilaj bolıp ótti.", "text_full": "\"Xon atlas\" ilaji bolıp ótti<br/><br/>Muhammed al-Xorezmiy atındaǵı TITU Nókis filialında Ózbekstan Respublikası shańaraq hám hayal-qızlar komiteti baslaması menen sonday-aq, Joqarı bilimlendiriw, ilim hám innovaciyalar ministrligi tárepinen jámiyetimizdiń belsendi aǵzaları esaplanǵan hayal-qızlarımızdıń milliy kóyleklerinde xalqımızdıń mıń ásirlik ótmishi, úrp-ádet hám dástúrleri sáwlelendirilgen kórinisler jámlengen \"Xon atlas\" hápteligi sheńberinde ilaj bolıp ótti.<br/><br/>Bul kibi ilajlar filialımızda óz jumıs iskerligin alıp barıp atırǵan bir-birinen gózzal ájapa-qarındaslarımızdıń talǵamı, estetik qaraslarında, ózine tán ózgeshelikleri hám kiyimler jámlenbesinde milliylikti mazmunı jaǵınan bayıtıwı menen áhmiyetli. \"Xon atlas\" onıń tákirarlanbas kórinisi, reńleri hám naǵısları kórgen kózdi quwantıp, bárshege báhárgi keypiyat baǵıshlaydı.", "img": "https://tatunf.uz/images/news/2024/april/5/24.jpg"}
    ]
}

export default News